import { ModeToggle } from "@/components/mode-toggle";
import "../globals.css";
import Link from "next/link";
export const metadata = {
  title: "Auth",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <section className="flex justify-between items-center p-2">
          <div>
            <Link className="text-2xl text-primary font-bold" href={"/"}>
              eSELL
            </Link>
          </div>
          <div>
            <ModeToggle></ModeToggle>
          </div>
        </section>
        <section>{children}</section>
      </body>
    </html>
  );
}
