import type { Metadata } from "next";

import "../globals.css";

import HomeNav from "@/components/home-nav";
import { ModeToggle } from "@/components/mode-toggle";

export const metadata: Metadata = {
  title: "eSELL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <section className="flex justify-between items-center p-2">
          <div>
            <h1 className="text-2xl text-primary font-bold">eSELL</h1>
          </div>
          <div>
            <ModeToggle></ModeToggle>
          </div>
        </section>
        <section className="flex flex-col md:flex-row lg:justify-between lg:items-start h-screen">
          <div className="bg-primary/15  px-4 rounded-md  lg:h-full fixed bottom-0 left-0 right-0 md:relative md:top-0 md:bottom-auto md:flex md:flex-col md:items-start md:p-4">
            <HomeNav />
          </div>
          <div className="flex-grow pt-16 md:pt-0 md:ml-4 md:pb-16 lg:pb-0">
            {children}
          </div>
        </section>
      </body>
    </html>
  );
}
